version: "3"
services:

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - "./mosquitto/config:/mosquitto/config/"
    networks:
      - localnet
    ports:
      - "1883:1883"

  node-red: 
    build: .
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    depends_on:
      - mosquitto
#    volumes:
#      - "./node-red:/data"
    networks:
      - localnet
    ports:
      - "1880:1880"
      
networks:
  localnet: